[project]
name = 'decentralized-voting-system'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.ProposalManager]
path = 'contracts/ProposalManager.clar'
clarity_version = 2
epoch = 2.5

[contracts.VotingToken]
path = 'contracts/VotingToken.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
